import { test, expect } from '@playwright/test';
test('task draft persists, snooze moves task, manual intake and waiting resolution work',async({page,request})=>{
  await request.post('/api/waiting',{data:{waiting_for:'Browser test partner',item_description:'Await test quotation'}});
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Mivel foglalkozz most?'})).toBeVisible();
  const card=page.locator('article').filter({has:page.getByRole('heading',{name:'Finalize premium configuration with Tom'})});
  await card.getByRole('button',{name:'Tervezet',exact:true}).click();
  await page.getByLabel('Választervezet',{exact:true}).fill('Hi Tom, please confirm the revised quote.');
  await page.getByRole('button',{name:'Tervezet mentése',exact:true}).click();
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('elmentve');
  await page.getByRole('button',{name:'Bezárás',exact:true}).click();
  await page.reload();await card.getByRole('button',{name:'Tervezet',exact:true}).click();
  await expect(page.getByLabel('Választervezet',{exact:true})).toHaveValue('Hi Tom, please confirm the revised quote.');
  await page.getByRole('dialog').getByRole('button',{name:'Holnap',exact:true}).click();
  await page.getByRole('button',{name:'Holnap',exact:true}).first().click();
  await expect(card).toBeVisible();
  await page.getByRole('button',{name:'Új jegyzet',exact:true}).click();
  await page.getByLabel('Feladat, átirat vagy továbbított üzenet',{exact:true}).fill('Buy notebooks for the office tomorrow.');
  await page.getByRole('button',{name:'Feladat létrehozása',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('status')).toContainText('elkészült');
  await page.getByRole('navigation').getByRole('button',{name:'Válaszra várok',exact:true}).click();
  const before=await page.getByRole('button',{name:'Megérkezett',exact:true}).count();
  expect(before).toBeGreaterThan(0);
  await page.locator('article').filter({hasText:'Browser test partner'}).last().getByRole('button',{name:'Megérkezett',exact:true}).click();
  await expect(page.getByRole('button',{name:'Megérkezett',exact:true})).toHaveCount(before-1);
});
test('search, urgent mode, calendar and mobile layout',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByRole('navigation').getByRole('button',{name:'Keresés',exact:true}).click();
  await page.getByRole('button',{name:'What did Tom say about cast iron grates?',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Finalize premium configuration with Tom'})).toBeVisible();
  await page.getByRole('navigation').getByRole('button',{name:'Sürgős mód',exact:true}).click();
  await page.getByRole('button',{name:'Bejövő hívás tesztelése',exact:true}).click();
  await expect(page.getByRole('heading',{name:'SÜRGŐS · Azonnali figyelem'})).toBeVisible();
  await page.getByRole('navigation').getByRole('button',{name:'Naptár',exact:true}).click();
  await expect(page.getByRole('button',{name:'Következő nap',exact:true})).toBeVisible();
  await page.getByRole('navigation').getByRole('button',{name:'Beállítások',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Kapcsolatok és beállítások'})).toBeVisible();
  await page.getByRole('navigation').getByRole('button',{name:'Feladataim',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Mivel foglalkozz most?'})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect(errors).toEqual([]);
  await page.screenshot({path:`test-results/mybrain-${test.info().project.name}.png`,fullPage:true});
});
test('PWA manifest and service worker shell are available',async({page,request})=>{
  const manifest=await request.get('/manifest.json');expect(manifest.ok()).toBe(true);expect((await manifest.json()).display).toBe('standalone');
  const push=await request.get('/api/push/config');expect(push.ok()).toBe(true);expect((await push.json()).publicKey).toBeTruthy();
  await page.goto('/');
  await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
  expect(await page.evaluate(async()=>(await caches.keys()).some(k=>k.startsWith('mybrain-')))).toBe(true);
  await page.reload();
  await page.context().setOffline(true);
  await page.reload();
  await expect(page.getByRole('heading',{name:'Mivel foglalkozz most?'})).toBeVisible();
  await page.context().setOffline(false);
});
test('personal memory supports adding, searching and forgetting compact examples',async({page})=>{
  await page.goto('/?tab=memory');
  await page.getByLabel('Téma vagy személy',{exact:true}).fill('Browser test Tom');
  await page.getByLabel('Rövid szabály (opcionális)',{exact:true}).fill('Reply briefly in English.');
  await page.getByLabel('Jó válaszpélda',{exact:true}).fill('Hi Tom, please confirm the revised quote.');
  await page.getByRole('button',{name:'Példa megjegyzése',exact:true}).click();
  const example=page.locator('.memory-list article').filter({hasText:'Browser test Tom'});
  await expect(example).toHaveCount(1);
  await page.getByLabel('Keresés a memóriában',{exact:true}).fill('Browser test Tom');
  await page.locator('main').getByRole('button',{name:'Keresés',exact:true}).click();
  await expect(example).toHaveCount(1);await example.getByRole('button',{name:'Elfelejtés',exact:true}).click();await expect(example).toHaveCount(0);
});
test('setup starts first sync only after AI and Google are both ready',async({page})=>{
  let starts=0;
  const state={pending:0,processing:0,done:0,failed:0,initialComplete:false,last:null};
  await page.route('**/api/settings',route=>route.fulfill({json:{provider:'openai',configured:{},aiReady:true,googleReady:true,googleConfigured:true,callbackUrl:'https://example.test/api/auth/google/callback',learnDrafts:false,demo:true,sync:state}}));
  await page.route('**/api/sync/start',route=>{starts++;return route.fulfill({json:{...state,initialComplete:true,done:2}});});
  await page.route('**/api/sync/status',route=>route.fulfill({json:{...state,initialComplete:true,done:2}}));
  await page.goto('/?tab=settings');await expect(page.getByRole('heading',{name:'Kapcsolatok és beállítások'})).toBeVisible();
  await expect.poll(()=>starts).toBe(1);
  await expect(page.getByText('✓ Google-engedély elmentve')).toBeVisible();
});
test('Android share target previews selected text without importing it automatically',async({page,request})=>{
  const manifest=await (await request.get('/manifest.json')).json();expect(manifest.share_target.method).toBe('POST');
  await page.goto('/');await page.evaluate(async()=>{await navigator.serviceWorker.ready;});await page.reload();
  await page.evaluate(()=>{const form=document.createElement('form');form.method='POST';form.action='/share';for(const [name,value] of Object.entries({title:'WhatsApp test conversation',text:'Tom: Please confirm the cast iron grids.'})){const input=document.createElement('input');input.name=name;input.value=value;form.append(input);}document.body.append(form);form.submit();});
  await expect(page.getByRole('heading',{name:'WhatsApp-szöveg importálása'})).toBeVisible();
  await expect(page.getByLabel('Átnézhető szöveg',{exact:true})).toHaveValue('Tom: Please confirm the cast iron grids.');
  await expect(page.getByRole('button',{name:'Kiválasztott szöveg elemzése'})).toBeEnabled();
});
